# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import random
from PySide6.QtCore import QEvent


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 438)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("QWidget#centralwidget {    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(3, 213, 255, 255), stop:1 rgba(226, 250, 255, 255));\n"
"}\n"
"\n"
"QLabel#pergunta {\n"
"    font-size: 40px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel#resposta {\n"
"    font-size: 40px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: 2px solid black;\n"
"    font-size: 20px;\n"
"    min-height: 45px;\n"
"    border-radius: 5;\n"
"    background-color: white;\n"
"    font-weight: bold;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.pergunta = QtWidgets.QLabel(parent=self.centralwidget)
        self.pergunta.setGeometry(QtCore.QRect(10, 20, 431, 91))
        self.pergunta.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pergunta.setObjectName("pergunta")
        self.frame_yes = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_yes.setGeometry(QtCore.QRect(50, 200, 160, 90))
        self.frame_yes.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_yes.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_yes.setObjectName("frame_yes")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_yes)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.botton_yes = QtWidgets.QPushButton(parent=self.frame_yes)
        self.botton_yes.setObjectName("botton_yes")
        self.horizontalLayout.addWidget(self.botton_yes)
        self.frame_no = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_no.setGeometry(QtCore.QRect(230, 200, 160, 90))
        self.frame_no.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_no.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_no.setObjectName("frame_no")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_no)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_no = QtWidgets.QPushButton(parent=self.frame_no)
        self.button_no.setObjectName("button_no")
        self.horizontalLayout_2.addWidget(self.button_no)
        self.resposta = QtWidgets.QLabel(parent=self.centralwidget)
        self.resposta.setGeometry(QtCore.QRect(10, 30, 431, 60))
        self.resposta.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.resposta.setObjectName("resposta")
        self.risada = QtWidgets.QLabel(parent=self.centralwidget)
        self.risada.setGeometry(QtCore.QRect(40, 110, 370, 300))
        self.risada.setText("")
        self.risada.setPixmap(QtGui.QPixmap(":/images/tom_cruise_smiling.png"))
        self.risada.setObjectName("risada")
        MainWindow.setCentralWidget(self.centralwidget)

        self.risada.setVisible(False)
        self.resposta.setVisible(False)

        self.button_no.clicked.connect(self.moveButton)
        self.botton_yes.clicked.connect(self.yes_choice)
        self.frame_no.installEventFilter(self.frame_no)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def moveButton(self):
        self.frame_no.move(random.randint(0, 300), random.randint(0, 300))

    def yes_choice(self):
        self.pergunta.setVisible(False)
        self.resposta.setVisible(True)
        self.risada.setVisible(True)
        self.button_no.setVisible(False)
        self.botton_yes.setVisible(False)

    def eventFilter(self, obj, event):
        if event.type() == QEvent.Enter and obj == self.frame_no:
            self.moveButton()
            return True
        else:
            return False

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pergunta.setText(_translate("MainWindow", "Você é idiota?"))
        self.botton_yes.setText(_translate("MainWindow", "Sim"))
        self.button_no.setText(_translate("MainWindow", "Não"))
        self.resposta.setText(_translate("MainWindow", "HAHAHA EU SABIA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())